/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations['liveness_api_v1_health_live_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations['readiness_api_v1_health_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signup */
    post: operations['signup_api_v1_auth_signup_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations['refresh_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/quota': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Quota */
    get: operations['quota_api_v1_auth_quota_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/diagnostics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Diagnosis */
    post: operations['create_diagnosis_api_v1_diagnostics_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/diagnostics/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stream Diagnosis
     * @description Stream one diagnostic turn as server-sent events.
     *
     *     The final ``result`` event carries the complete response; the events
     *     before it report progress only. See ``app.models.schemas.streaming`` for
     *     why no partial answer is ever streamed.
     */
    post: operations['stream_diagnosis_api_v1_diagnostics_stream_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/diagnostics/{session_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Diagnostic Session */
    get: operations['get_diagnostic_session_api_v1_diagnostics__session_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calculations/cable-sizing': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Size Cable */
    post: operations['size_cable_api_v1_calculations_cable_sizing_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calculations/vfd-selection': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Select Vfd */
    post: operations['select_vfd_api_v1_calculations_vfd_selection_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calculations/panel-bom': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Build Panel Bom */
    post: operations['build_panel_bom_api_v1_calculations_panel_bom_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search Documents */
    post: operations['search_documents_api_v1_search_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ingestion/crawl-jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Crawl Job */
    post: operations['create_crawl_job_api_v1_ingestion_crawl_jobs_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ingestion/verification-queue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Verification Queue */
    get: operations['list_verification_queue_api_v1_ingestion_verification_queue_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ingestion/promotions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Promote Document */
    post: operations['promote_document_api_v1_ingestion_promotions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/verification/queue/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * My Queue
     * @description Return the caller's outstanding batch.
     */
    get: operations['my_queue_api_v1_verification_queue_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/verification/items/{item_id}/label': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Label Item
     * @description Record the caller's label for one item.
     *
     *     Raises:
     *         HTTPException: 404 if the item does not exist, 403 if it belongs to
     *             another verifier, 422 if an escalating label carries no note.
     */
    post: operations['label_item_api_v1_verification_items__item_id__label_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/verification/escalations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Escalations
     * @description Return every item awaiting lead review.
     *
     *     Raises:
     *         HTTPException: 403 unless the caller holds the reviewer role.
     *
     *     Gated because an escalation names content a verifier believed wrong, and
     *     the queue spans every verifier's work. AI-012's rule is that these are
     *     resolved by a lead rather than by whoever raised them, which only holds if
     *     the view is restricted to leads.
     */
    get: operations['list_escalations_api_v1_verification_escalations_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/images': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload Image
     * @description Accept a photo of an equipment display.
     *
     *     The declared content type is deliberately not passed on: the domain
     *     sniffs the bytes, and forwarding a client-supplied type would invite a
     *     future reader to trust it.
     */
    post: operations['upload_image_api_v1_images_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AppliedFactor
     * @description A derating or correction factor, with the clause it came from.
     */
    AppliedFactor: {
      /** Name */
      name: string;
      /** Value */
      value: string;
      source: components['schemas']['Citation'];
    };
    /** Body_upload_image_api_v1_images_post */
    Body_upload_image_api_v1_images_post: {
      /** File */
      file: string;
    };
    /**
     * BomLine
     * @description One line of a bill of materials.
     */
    BomLine: {
      /** Part Reference */
      part_reference: string;
      /** Description */
      description: string;
      /** Quantity */
      quantity: number;
      source: components['schemas']['Citation'];
    };
    /**
     * CableSizingRequest
     * @description Inputs for a feeder cable sizing.
     */
    CableSizingRequest: {
      /** Design Current A */
      design_current_a: number | string;
      /** Length M */
      length_m: number | string;
      /** Supply Voltage V */
      supply_voltage_v: number | string;
      installation_method: components['schemas']['InstallationMethod'];
      /** Ambient Temp C */
      ambient_temp_c: number | string;
      /**
       * Grouped Circuits
       * @default 1
       */
      grouped_circuits: number;
      /** @default copper */
      conductor_material: components['schemas']['ConductorMaterial'];
      /**
       * Insulation Rating C
       * @default 90
       */
      insulation_rating_c: number;
      /**
       * Power Factor
       * @default 0.9
       */
      power_factor: number | string;
      /**
       * Three Phase
       * @default true
       */
      three_phase: boolean;
    };
    /**
     * CableSizingResponse
     * @description Cable sizing as returned to the caller.
     */
    CableSizingResponse: {
      result: components['schemas']['CableSizingResult'];
      /** Voltage Drop V */
      voltage_drop_v: string;
      /** Voltage Drop Percent */
      voltage_drop_percent: string;
      /** Sources */
      sources: components['schemas']['Citation'][];
    };
    /**
     * CableSizingResult
     * @description Output of the pure sizing function.
     */
    CableSizingResult: {
      /** Cross Section Mm2 */
      cross_section_mm2: string;
      /** Derated Ampacity A */
      derated_ampacity_a: string;
      /** Applied Factors */
      applied_factors: components['schemas']['AppliedFactor'][];
    };
    /**
     * Citation
     * @description A resolvable pointer back into a source document.
     */
    Citation: {
      /** Document Id */
      document_id: string;
      /** Document Title */
      document_title: string;
      /** Manufacturer */
      manufacturer: string;
      /** Page */
      page?: number | null;
      /** Section */
      section?: string | null;
    };
    /**
     * ConductorMaterial
     * @description Conductor metal.
     * @enum {string}
     */
    ConductorMaterial: 'copper' | 'aluminium';
    /**
     * ConfidenceBreakdown
     * @description Overall confidence with the per-signal components behind it.
     */
    ConfidenceBreakdown: {
      /** Overall */
      overall: number;
      /** Retrieval Score */
      retrieval_score: number;
      /** Passage Agreement */
      passage_agreement: number;
      /** Citation Density */
      citation_density: number;
    };
    /**
     * CrawlJobRequest
     * @description Request to queue a crawl.
     */
    CrawlJobRequest: {
      /** Source Id */
      source_id: string;
      /**
       * Seed Urls
       * @default []
       */
      seed_urls: string[];
      /**
       * Max Depth
       * @default 2
       */
      max_depth: number;
    };
    /**
     * CrawlJobResponse
     * @description A queued crawl job.
     */
    CrawlJobResponse: {
      /** Id */
      id: string;
      status: components['schemas']['CrawlJobStatus'];
    };
    /**
     * CrawlJobStatus
     * @description Lifecycle state of a crawl job.
     * @enum {string}
     */
    CrawlJobStatus: 'queued' | 'running' | 'succeeded' | 'failed';
    /**
     * DependencyState
     * @description Reachability of a dependency.
     * @enum {string}
     */
    DependencyState: 'up' | 'down';
    /**
     * DiagnosisStep
     * @description One step an engineer should carry out.
     *
     *     Attributes:
     *         order: 1-indexed position. Explicit rather than implied by array index
     *             so a step cannot be silently reordered by a serialisation layer.
     *         instruction: What to do, in one imperative sentence.
     *         rationale: Why this step, so the engineer can judge whether it applies
     *             to their situation rather than following blindly.
     *         citation_ids: Passage ids supporting this step. Required, non-empty,
     *             and deduplicated — a step with no source is exactly what
     *             cite-or-refuse exists to prevent, and the same id repeated would
     *             overstate how much evidence there is.
     *         severity: Urgency of this step. Required rather than defaulted: a
     *             missing severity defaulting to ``INFO`` would render an arc-flash
     *             warning in the same colour as a note.
     */
    DiagnosisStep: {
      /** Order */
      order: number;
      /** Instruction */
      instruction: string;
      /** Rationale */
      rationale: string;
      /** Citation Ids */
      citation_ids: string[];
      severity: components['schemas']['Severity'];
    };
    /**
     * DiagnosticRequest
     * @description A single diagnostic question.
     *
     *     Attributes:
     *         session_id: The conversation to append to, or ``None`` to start one.
     *         symptom: What the engineer is describing.
     *         equipment: Optional context about the unit.
     *         locale: The language to answer in. Explicit on every request rather
     *             than defaulted server-side: a default means a caller that forgot
     *             to send one gets English, which for an Arabic-speaking engineer
     *             looks like working software until someone reads the answer.
     */
    DiagnosticRequest: {
      /** Session Id */
      session_id?: string | null;
      /** Symptom */
      symptom: string;
      equipment?: components['schemas']['EquipmentContext'] | null;
      /** @default en */
      locale: components['schemas']['Locale'];
    };
    /**
     * DiagnosticResponse
     * @description A completed diagnostic turn as returned to the caller.
     *
     *     This is the type the frontend renders, and the schema constraining
     *     generation is derived from the ``StructuredDiagnosis`` embedded here — the
     *     same model, not a copy of it. That is what makes "the constraint and the rendered type
     *     cannot drift" true rather than aspirational: there is one definition, and
     *     ``packages/shared-types`` regenerates its TypeScript from this schema.
     *
     *     Attributes:
     *         session_id: The conversation this turn belongs to.
     *         answer: Prose form of the answer, with resolved citations. Absent on a
     *             refusal — a required-but-empty answer object would be one more
     *             thing the frontend has to inspect before deciding what to show.
     *         diagnosis: The structured form, when the model produced schema-valid
     *             output. ``None`` on a refusal, which is the only case where the
     *             frontend renders the refusal template instead of the card.
     *         confidence: Per-signal confidence behind the decision.
     *         low_confidence: Whether to show the uncertainty banner.
     *         refusal_message: Rendered refusal text, present exactly when
     *             ``diagnosis`` is absent.
     */
    DiagnosticResponse: {
      /** Session Id */
      session_id: string;
      answer?: components['schemas']['VerifiedAnswer'] | null;
      diagnosis?: components['schemas']['StructuredDiagnosis'] | null;
      confidence: components['schemas']['ConfidenceBreakdown'];
      /** Low Confidence */
      low_confidence: boolean;
      /** Refusal Message */
      refusal_message?: string | null;
    };
    /**
     * DiagnosticSession
     * @description A diagnostic conversation and its ordered turns.
     */
    DiagnosticSession: {
      /** Id */
      id: string;
      /** Turns */
      turns: components['schemas']['DiagnosticTurn'][];
    };
    /**
     * DiagnosticTurn
     * @description One stored exchange in a session.
     */
    DiagnosticTurn: {
      request: components['schemas']['DiagnosticRequest'];
      response: components['schemas']['DiagnosticResponse'];
    };
    /**
     * DutyClass
     * @description Drive duty rating.
     * @enum {string}
     */
    DutyClass: 'normal' | 'heavy';
    /**
     * EnclosureConstraints
     * @description Physical and vendor constraints on the enclosure.
     */
    EnclosureConstraints: {
      /** Width Mm */
      width_mm: number;
      /** Height Mm */
      height_mm: number;
      /** Depth Mm */
      depth_mm: number;
      /** Ingress Rating */
      ingress_rating: string;
      /**
       * Preferred Vendors
       * @default []
       */
      preferred_vendors: string[];
      /**
       * Ambient Temp C
       * @default 35
       */
      ambient_temp_c: number | string;
      /**
       * Max Internal Temp C
       * @default 50
       */
      max_internal_temp_c: number | string;
    };
    /**
     * EquipmentContext
     * @description What the engineer is working on.
     */
    EquipmentContext: {
      /** Manufacturer */
      manufacturer?: string | null;
      /** Model */
      model?: string | null;
      /**
       * Fault Codes
       * @default []
       */
      fault_codes: string[];
    };
    /**
     * EscalationPage
     * @description Items awaiting lead-engineer review.
     */
    EscalationPage: {
      /** Items */
      items: components['schemas']['QueueItem'][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthResponse
     * @description Result of a liveness or readiness probe.
     */
    HealthResponse: {
      status: components['schemas']['DependencyState'];
      /**
       * Dependencies
       * @default {}
       */
      dependencies: {
        [key: string]: components['schemas']['DependencyState'];
      };
    };
    /**
     * ImageUploadResponse
     * @description What an upload returns.
     *
     *     Attributes:
     *         image_id: The handle to pass to the chat endpoint.
     */
    ImageUploadResponse: {
      /** Image Id */
      image_id: string;
    };
    /**
     * InstallationMethod
     * @description IEC 60364-5-52 reference installation method.
     * @enum {string}
     */
    InstallationMethod: 'A1' | 'A2' | 'B1' | 'B2' | 'C' | 'D1' | 'D2' | 'E' | 'F' | 'G';
    /**
     * LabelRequest
     * @description A verifier's judgement on one item.
     */
    LabelRequest: {
      label: components['schemas']['VerificationLabel'];
      /**
       * Note
       * @default
       */
      note: string;
    };
    /**
     * LabelResponse
     * @description The outcome of recording a label.
     */
    LabelResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
      /** Label */
      label: string | null;
    };
    /**
     * LoadScheduleItem
     * @description One load on a panel's schedule.
     */
    LoadScheduleItem: {
      /** Tag */
      tag: string;
      /** Description */
      description: string;
      /** Power Kw */
      power_kw?: number | string | null;
      /** Current A */
      current_a?: number | string | null;
      /** Dissipation W */
      dissipation_w?: number | string | null;
    };
    /**
     * Locale
     * @description A language a response may be generated in.
     *
     *     Deliberately a closed set. An open string would let a caller pass anything
     *     and get whatever the model felt like, which for a language the corpus does
     *     not support is worse than refusing.
     * @enum {string}
     */
    Locale: 'en' | 'ar' | 'he';
    /**
     * LoginRequest
     * @description Exchange credentials for a token pair.
     */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * PanelBomRequest
     * @description Inputs for BOM generation.
     */
    PanelBomRequest: {
      /** Loads */
      loads: components['schemas']['LoadScheduleItem'][];
      constraints: components['schemas']['EnclosureConstraints'];
    };
    /**
     * PanelBomResponse
     * @description BOM as returned to the caller.
     */
    PanelBomResponse: {
      result: components['schemas']['PanelBomResult'];
      /** Sources */
      sources: components['schemas']['Citation'][];
    };
    /**
     * PanelBomResult
     * @description Output of the pure BOM function.
     */
    PanelBomResult: {
      /** Lines */
      lines: components['schemas']['BomLine'][];
      /** Heat Load W */
      heat_load_w: string;
    };
    /**
     * PromotionRequest
     * @description Request to make a verified staged document live.
     */
    PromotionRequest: {
      /** Staged Document Id */
      staged_document_id: string;
      /**
       * Notes
       * @default
       */
      notes: string;
    };
    /**
     * PromotionResponse
     * @description Result of a promotion, including the audit entry written.
     */
    PromotionResponse: {
      /** Production Document Id */
      production_document_id: string;
      /** Revision */
      revision: number;
      /** Audit Id */
      audit_id: string;
    };
    /**
     * QueueItem
     * @description One chunk in a verifier's queue.
     */
    QueueItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Chunk Id */
      chunk_id: string | null;
      /** Status */
      status: string;
      /** Assigned At */
      assigned_at: string | null;
    };
    /**
     * QueuePage
     * @description A verifier's outstanding batch.
     */
    QueuePage: {
      /** Items */
      items: components['schemas']['QueueItem'][];
    };
    /**
     * QuotaStatus
     * @description Free-tier usage, as counted on the server.
     */
    QuotaStatus: {
      /** Questions Used */
      questions_used: number;
      /** Question Limit */
      question_limit: number;
      /** Questions Remaining */
      questions_remaining: number;
    };
    /**
     * RefreshRequest
     * @description Exchange a refresh token for a new pair.
     */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /**
     * RetrievedPassage
     * @description One passage returned by retrieval, with its citation and score.
     */
    RetrievedPassage: {
      /** Id */
      id: string;
      /** Text */
      text: string;
      /** Score */
      score: number;
      citation: components['schemas']['Citation'];
    };
    /**
     * SearchFilters
     * @description Optional restrictions applied to a search.
     */
    SearchFilters: {
      /**
       * Manufacturers
       * @default []
       */
      manufacturers: string[];
      /**
       * Document Types
       * @default []
       */
      document_types: string[];
      /** Published After */
      published_after?: string | null;
    };
    /**
     * SearchRequest
     * @description A search issued by a caller.
     */
    SearchRequest: {
      /** Query */
      query: string;
      filters?: components['schemas']['SearchFilters'] | null;
      /** Top K */
      top_k?: number | null;
    };
    /**
     * SearchResponse
     * @description Ranked search results.
     */
    SearchResponse: {
      /** Passages */
      passages: components['schemas']['RetrievedPassage'][];
      /** Total */
      total: number;
    };
    /**
     * Severity
     * @description How urgent a finding is.
     *
     *     A closed set: the frontend renders each with its own colour token, so a
     *     free-text severity would arrive as an unstyled string.
     * @enum {string}
     */
    Severity: 'critical' | 'warning' | 'info';
    /**
     * SignupRequest
     * @description Create an account, optionally claiming an anonymous trial session.
     */
    SignupRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Full Name */
      full_name?: string | null;
      /** Claim Session Id */
      claim_session_id?: string | null;
      /** Claim Secret */
      claim_secret?: string | null;
    };
    /**
     * StructuredDiagnosis
     * @description A complete diagnostic response, as constrained at generation time.
     *
     *     Attributes:
     *         summary: One-paragraph answer to the engineer's question.
     *         summary_citation_ids: Passages supporting the summary. Required for the
     *             same reason as a step's.
     *         steps: Ordered actions. Non-empty: a diagnosis with no action is not a
     *             diagnosis, and the refuse path exists for when there is nothing to
     *             say.
     *         severity: Overall urgency, for the card header. Required, as a step's is.
     *         equipment_model: The model this diagnosis applies to, echoed back so an
     *             engineer can see the assistant understood which unit they meant.
     */
    StructuredDiagnosis: {
      /** Summary */
      summary: string;
      /** Summary Citation Ids */
      summary_citation_ids: string[];
      /** Steps */
      steps: components['schemas']['DiagnosisStep'][];
      severity: components['schemas']['Severity'];
      /** Equipment Model */
      equipment_model?: string | null;
    };
    /**
     * TokenPair
     * @description A short-lived access token and the refresh token that renews it.
     */
    TokenPair: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /** Expires In */
      expires_in: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VerificationDecision
     * @description A reviewer's decision on a staged document.
     * @enum {string}
     */
    VerificationDecision: 'approved' | 'rejected';
    /**
     * VerificationItem
     * @description A staged document awaiting or holding a review decision.
     */
    VerificationItem: {
      /** Id */
      id: string;
      /** Staged Document Id */
      staged_document_id: string;
      /** Claimed By */
      claimed_by?: string | null;
      verdict?: components['schemas']['VerificationVerdict'] | null;
    };
    /**
     * VerificationLabel
     * @description A verifier's judgement on one chunk.
     *
     *     Deliberately three values, not a numeric confidence. A scale invites
     *     averaging, and there is no meaningful average of "the source says 63 A"
     *     and "the source does not mention this" — the second is a citation failure
     *     whatever the first says.
     * @enum {string}
     */
    VerificationLabel: 'correct' | 'incorrect' | 'uncertain';
    /**
     * VerificationQueuePage
     * @description A page of the verification queue.
     */
    VerificationQueuePage: {
      /** Items */
      items: components['schemas']['VerificationItem'][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /**
     * VerificationVerdict
     * @description A reviewer's decision plus their notes.
     */
    VerificationVerdict: {
      decision: components['schemas']['VerificationDecision'];
      /**
       * Notes
       * @default
       */
      notes: string;
    };
    /**
     * VerifiedAnswer
     * @description An answer whose every citation resolves to supplied evidence.
     *
     *     Attributes:
     *         text: The prose answer. Non-blank for the same reason the structured
     *             summary is: "   " renders as an empty card.
     *         citations: Resolved citations backing the text.
     */
    VerifiedAnswer: {
      /** Text */
      text: string;
      /** Citations */
      citations: components['schemas']['Citation'][];
    };
    /**
     * VfdSelectionRequest
     * @description Inputs for a drive selection.
     */
    VfdSelectionRequest: {
      /** Motor Power Kw */
      motor_power_kw: number | string;
      /** Supply Voltage V */
      supply_voltage_v: number | string;
      /** Motor Efficiency */
      motor_efficiency: number | string;
      /** Motor Power Factor */
      motor_power_factor: number | string;
      /** @default normal */
      duty_class: components['schemas']['DutyClass'];
      /**
       * Altitude M
       * @default 0
       */
      altitude_m: number | string;
      /**
       * Ambient Temp C
       * @default 40
       */
      ambient_temp_c: number | string;
    };
    /**
     * VfdSelectionResponse
     * @description Drive selection as returned to the caller.
     */
    VfdSelectionResponse: {
      result: components['schemas']['VfdSelectionResult'];
      /** Sources */
      sources: components['schemas']['Citation'][];
    };
    /**
     * VfdSelectionResult
     * @description Output of the pure selection function.
     */
    VfdSelectionResult: {
      /** Frame Reference */
      frame_reference: string;
      /** Rated Output Current A */
      rated_output_current_a: string;
      /** Applied Factors */
      applied_factors: components['schemas']['AppliedFactor'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  liveness_api_v1_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  readiness_api_v1_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  signup_api_v1_auth_signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPair'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPair'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPair'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  quota_api_v1_auth_quota_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuotaStatus'];
        };
      };
    };
  };
  create_diagnosis_api_v1_diagnostics_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DiagnosticRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DiagnosticResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stream_diagnosis_api_v1_diagnostics_stream_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DiagnosticRequest'];
      };
    };
    responses: {
      /** @description A stream of server-sent events. Progress events report the stage; the final `result` event carries the complete DiagnosticResponse. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': {
            /**
             * Event
             * @enum {string}
             */
            event: 'retrieving' | 'generated' | 'refused' | 'result';
            /** Data */
            data?: {
              [key: string]: unknown;
            };
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_diagnostic_session_api_v1_diagnostics__session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DiagnosticSession'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  size_cable_api_v1_calculations_cable_sizing_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CableSizingRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CableSizingResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  select_vfd_api_v1_calculations_vfd_selection_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VfdSelectionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VfdSelectionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  build_panel_bom_api_v1_calculations_panel_bom_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PanelBomRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PanelBomResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  search_documents_api_v1_search_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SearchRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_crawl_job_api_v1_ingestion_crawl_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CrawlJobRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CrawlJobResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_verification_queue_api_v1_ingestion_verification_queue_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VerificationQueuePage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  promote_document_api_v1_ingestion_promotions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PromotionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PromotionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  my_queue_api_v1_verification_queue_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QueuePage'];
        };
      };
    };
  };
  label_item_api_v1_verification_items__item_id__label_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LabelRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_escalations_api_v1_verification_escalations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EscalationPage'];
        };
      };
    };
  };
  upload_image_api_v1_images_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_image_api_v1_images_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImageUploadResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
