"""add tenants, escalation items, source health; scope customer tables by tenant

Revision ID: 06497046bf4d
Revises: b9d1ba0c1ef2
Create Date: 2026-08-25 23:07:14.945972
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "06497046bf4d"
down_revision: str | None = "b9d1ba0c1ef2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_health",
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("documents_indexed", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_health")),
    )
    op.create_index(op.f("ix_source_health_source_id"), "source_health", ["source_id"], unique=True)
    op.create_table(
        "tenants",
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)

    # A default tenant so existing rows have an owner to be assigned to.
    # Single-tenant installs keep using it; multi-tenant ones migrate rows off
    # it deliberately. Without this the backfill below has nothing to set.
    op.execute(
        sa.text(
            "INSERT INTO tenants (id, slug, name, is_active, created_at, updated_at) "
            "VALUES (gen_random_uuid(), 'default', 'Default tenant', true, now(), now()) "
            "ON CONFLICT (slug) DO NOTHING"
        )
    )
    op.create_table(
        "escalation_items",
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("raised_by_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raised_by_id"],
            ["users.id"],
            name=op.f("fk_escalation_items_raised_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["diagnostic_sessions.id"],
            name=op.f("fk_escalation_items_session_id_diagnostic_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_escalation_items_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escalation_items")),
    )
    op.create_index(
        op.f("ix_escalation_items_raised_by_id"), "escalation_items", ["raised_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_escalation_items_reason"), "escalation_items", ["reason"], unique=False
    )
    op.create_index(
        op.f("ix_escalation_items_session_id"), "escalation_items", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_escalation_items_status"), "escalation_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_escalation_items_tenant_id"), "escalation_items", ["tenant_id"], unique=False
    )
    # Added nullable, backfilled, then constrained. A direct NOT NULL add
    # fails on any table that already has rows -- verified against a populated
    # database, where it raised NotNullViolation.
    op.add_column("calculation_records", sa.Column("tenant_id", sa.Uuid(), nullable=True))
    op.execute(
        sa.text(
            "UPDATE calculation_records SET tenant_id = (SELECT id FROM tenants "
            "WHERE slug = 'default') WHERE tenant_id IS NULL"
        )
    )
    op.alter_column("calculation_records", "tenant_id", nullable=False)
    op.create_index(
        op.f("ix_calculation_records_tenant_id"), "calculation_records", ["tenant_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_calculation_records_tenant_id_tenants"),
        "calculation_records",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # Added nullable, backfilled, then constrained. A direct NOT NULL add
    # fails on any table that already has rows -- verified against a populated
    # database, where it raised NotNullViolation.
    op.add_column("diagnostic_sessions", sa.Column("tenant_id", sa.Uuid(), nullable=True))
    op.execute(
        sa.text(
            "UPDATE diagnostic_sessions SET tenant_id = (SELECT id FROM tenants "
            "WHERE slug = 'default') WHERE tenant_id IS NULL"
        )
    )
    op.alter_column("diagnostic_sessions", "tenant_id", nullable=False)
    op.create_index(
        op.f("ix_diagnostic_sessions_tenant_id"), "diagnostic_sessions", ["tenant_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_diagnostic_sessions_tenant_id_tenants"),
        "diagnostic_sessions",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # Added nullable, backfilled, then constrained. A direct NOT NULL add
    # fails on any table that already has rows -- verified against a populated
    # database, where it raised NotNullViolation.
    op.add_column("users", sa.Column("tenant_id", sa.Uuid(), nullable=True))
    op.execute(
        sa.text(
            "UPDATE users SET tenant_id = (SELECT id FROM tenants "
            "WHERE slug = 'default') WHERE tenant_id IS NULL"
        )
    )
    op.alter_column("users", "tenant_id", nullable=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_users_tenant_id_tenants"),
        "users",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_tenant_id_tenants"), "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_column("users", "tenant_id")
    op.drop_constraint(
        op.f("fk_diagnostic_sessions_tenant_id_tenants"), "diagnostic_sessions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_diagnostic_sessions_tenant_id"), table_name="diagnostic_sessions")
    op.drop_column("diagnostic_sessions", "tenant_id")
    op.drop_constraint(
        op.f("fk_calculation_records_tenant_id_tenants"), "calculation_records", type_="foreignkey"
    )
    op.drop_index(op.f("ix_calculation_records_tenant_id"), table_name="calculation_records")
    op.drop_column("calculation_records", "tenant_id")
    op.drop_index(op.f("ix_escalation_items_tenant_id"), table_name="escalation_items")
    op.drop_index(op.f("ix_escalation_items_status"), table_name="escalation_items")
    op.drop_index(op.f("ix_escalation_items_session_id"), table_name="escalation_items")
    op.drop_index(op.f("ix_escalation_items_reason"), table_name="escalation_items")
    op.drop_index(op.f("ix_escalation_items_raised_by_id"), table_name="escalation_items")
    op.drop_table("escalation_items")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_source_health_source_id"), table_name="source_health")
    op.drop_table("source_health")
    # ### end Alembic commands ###
