"""add auth: password hash, refresh tokens, anonymous sessions, free tier quota

Revision ID: 6378472e8d97
Revises: 06497046bf4d
Create Date: 2026-08-25 23:29:23.562786
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6378472e8d97"
down_revision: str | None = "06497046bf4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_refresh_tokens_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_tenant_id"), "refresh_tokens", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "anonymous_sessions",
        sa.Column("diagnostic_session_id", sa.Uuid(), nullable=False),
        sa.Column("claimed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_expired", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by_user_id"],
            ["users.id"],
            name=op.f("fk_anonymous_sessions_claimed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["diagnostic_session_id"],
            ["diagnostic_sessions.id"],
            name=op.f("fk_anonymous_sessions_diagnostic_session_id_diagnostic_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_anonymous_sessions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anonymous_sessions")),
    )
    op.create_index(
        op.f("ix_anonymous_sessions_claimed_by_user_id"),
        "anonymous_sessions",
        ["claimed_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anonymous_sessions_diagnostic_session_id"),
        "anonymous_sessions",
        ["diagnostic_session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_anonymous_sessions_tenant_id"), "anonymous_sessions", ["tenant_id"], unique=False
    )
    op.alter_column("diagnostic_sessions", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(
        op.f("fk_diagnostic_sessions_user_id_users"), "diagnostic_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_diagnostic_sessions_user_id_users"),
        "diagnostic_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # server_default, not just the ORM default: a NOT NULL add must give
    # EXISTING rows a value, and the Python-side default only applies to
    # rows this application inserts. Reproduced against a populated
    # tenants table, where the plain add raised NotNullViolation.
    op.add_column(
        "tenants",
        sa.Column(
            "free_questions_used",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "free_question_limit",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("10"),
        ),
    )
    op.add_column("users", sa.Column("password_hash", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    op.drop_column("tenants", "free_question_limit")
    op.drop_column("tenants", "free_questions_used")
    op.drop_constraint(
        op.f("fk_diagnostic_sessions_user_id_users"), "diagnostic_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_diagnostic_sessions_user_id_users"),
        "diagnostic_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("diagnostic_sessions", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("ix_anonymous_sessions_tenant_id"), table_name="anonymous_sessions")
    op.drop_index(
        op.f("ix_anonymous_sessions_diagnostic_session_id"), table_name="anonymous_sessions"
    )
    op.drop_index(op.f("ix_anonymous_sessions_claimed_by_user_id"), table_name="anonymous_sessions")
    op.drop_table("anonymous_sessions")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_tenant_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
