"""Verification queue: chunk-level assignment.

Adds the columns BE-007 needs to distribute chunks across ten verifiers:
which chunk, whose queue it sits in, when it was assigned, its status, and
the label applied.

``chunk_id`` is UNIQUE, and that constraint is the whole double-assignment
guarantee. Ten people work this queue concurrently and the assignment job may
run twice — a retry, an overlapping schedule, two operators — and an
application-level "check then insert" has a window between the two statements.
The constraint has none.

``staged_document_id`` relaxes to nullable because the unit of review is now a
chunk: one staged document yields many chunks, so the old 1:1 no longer holds.
The check constraint keeps a row from identifying nothing at all.

Revision ID: 6b538ddb9363
Revises: c14f7a2b9e30
Create Date: 2026-08-27 12:40:34.633988
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6b538ddb9363"
down_revision: str | None = "c14f7a2b9e30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("verification_items", sa.Column("chunk_id", sa.String(length=128), nullable=True))
    op.add_column("verification_items", sa.Column("assigned_to_id", sa.Uuid(), nullable=True))
    op.add_column(
        "verification_items", sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True)
    )
    # server_default backfills any row already in the table; without it this
    # is a NOT NULL column with no value for existing rows and the migration
    # fails on a non-empty table. Dropped immediately afterwards so the
    # application stays the only thing that decides a new row's status.
    op.add_column(
        "verification_items",
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
    )
    op.alter_column("verification_items", "status", server_default=None)
    op.add_column("verification_items", sa.Column("label", sa.String(length=20), nullable=True))
    op.alter_column(
        "verification_items", "staged_document_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_index(op.f("ix_verification_items_staged_document_id"), table_name="verification_items")
    op.create_index(
        op.f("ix_verification_items_staged_document_id"),
        "verification_items",
        ["staged_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_items_assigned_to_id"),
        "verification_items",
        ["assigned_to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_items_chunk_id"), "verification_items", ["chunk_id"], unique=True
    )
    op.create_index(
        op.f("ix_verification_items_label"), "verification_items", ["label"], unique=False
    )
    op.create_index(
        op.f("ix_verification_items_status"), "verification_items", ["status"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_verification_items_assigned_to_id_users"),
        "verification_items",
        "users",
        ["assigned_to_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        op.f("ck_verification_items_target_present"),
        "verification_items",
        "chunk_id IS NOT NULL OR staged_document_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_verification_items_target_present"), "verification_items", type_="check"
    )
    op.drop_constraint(
        op.f("fk_verification_items_assigned_to_id_users"), "verification_items", type_="foreignkey"
    )
    op.drop_index(op.f("ix_verification_items_status"), table_name="verification_items")
    op.drop_index(op.f("ix_verification_items_label"), table_name="verification_items")
    op.drop_index(op.f("ix_verification_items_chunk_id"), table_name="verification_items")
    op.drop_index(op.f("ix_verification_items_assigned_to_id"), table_name="verification_items")
    op.drop_index(op.f("ix_verification_items_staged_document_id"), table_name="verification_items")
    op.create_index(
        op.f("ix_verification_items_staged_document_id"),
        "verification_items",
        ["staged_document_id"],
        unique=True,
    )
    op.alter_column(
        "verification_items", "staged_document_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("verification_items", "label")
    op.drop_column("verification_items", "status")
    op.drop_column("verification_items", "assigned_at")
    op.drop_column("verification_items", "assigned_to_id")
    op.drop_column("verification_items", "chunk_id")
    # ### end Alembic commands ###
