"""initial schema

Revision ID: b9d1ba0c1ef2
Revises:
Create Date: 2026-08-25 10:58:24.061662
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b9d1ba0c1ef2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_jobs",
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_jobs")),
    )
    op.create_index(op.f("ix_crawl_jobs_source_id"), "crawl_jobs", ["source_id"], unique=False)
    op.create_index(op.f("ix_crawl_jobs_status"), "crawl_jobs", ["status"], unique=False)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "calculation_records",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_calculation_records_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculation_records")),
    )
    op.create_index(
        op.f("ix_calculation_records_kind"), "calculation_records", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_calculation_records_user_id"), "calculation_records", ["user_id"], unique=False
    )
    op.create_table(
        "diagnostic_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_diagnostic_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnostic_sessions")),
    )
    op.create_index(
        op.f("ix_diagnostic_sessions_user_id"), "diagnostic_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "staged_documents",
        sa.Column("crawl_job_id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("ingested_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_job_id"],
            ["crawl_jobs.id"],
            name=op.f("fk_staged_documents_crawl_job_id_crawl_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingested_by_id"],
            ["users.id"],
            name=op.f("fk_staged_documents_ingested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staged_documents")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_staged_documents_content_hash")),
    )
    op.create_index(
        op.f("ix_staged_documents_crawl_job_id"), "staged_documents", ["crawl_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_staged_documents_ingested_by_id"),
        "staged_documents",
        ["ingested_by_id"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "diagnostic_turns",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["diagnostic_sessions.id"],
            name=op.f("fk_diagnostic_turns_session_id_diagnostic_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnostic_turns")),
    )
    op.create_index(
        op.f("ix_diagnostic_turns_session_id"), "diagnostic_turns", ["session_id"], unique=False
    )
    op.create_table(
        "promotion_audits",
        sa.Column("staged_document_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("production_document_id", sa.String(length=100), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_promotion_audits_reviewer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["staged_document_id"],
            ["staged_documents.id"],
            name=op.f("fk_promotion_audits_staged_document_id_staged_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotion_audits")),
    )
    op.create_index(
        op.f("ix_promotion_audits_production_document_id"),
        "promotion_audits",
        ["production_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promotion_audits_reviewer_id"), "promotion_audits", ["reviewer_id"], unique=False
    )
    op.create_index(
        op.f("ix_promotion_audits_staged_document_id"),
        "promotion_audits",
        ["staged_document_id"],
        unique=False,
    )
    op.create_table(
        "verification_items",
        sa.Column("staged_document_id", sa.Uuid(), nullable=False),
        sa.Column("claimed_by_id", sa.Uuid(), nullable=True),
        sa.Column("decision", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by_id"],
            ["users.id"],
            name=op.f("fk_verification_items_claimed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["staged_document_id"],
            ["staged_documents.id"],
            name=op.f("fk_verification_items_staged_document_id_staged_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_items")),
    )
    op.create_index(
        op.f("ix_verification_items_claimed_by_id"),
        "verification_items",
        ["claimed_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_items_decision"), "verification_items", ["decision"], unique=False
    )
    op.create_index(
        op.f("ix_verification_items_staged_document_id"),
        "verification_items",
        ["staged_document_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_items_staged_document_id"), table_name="verification_items")
    op.drop_index(op.f("ix_verification_items_decision"), table_name="verification_items")
    op.drop_index(op.f("ix_verification_items_claimed_by_id"), table_name="verification_items")
    op.drop_table("verification_items")
    op.drop_index(op.f("ix_promotion_audits_staged_document_id"), table_name="promotion_audits")
    op.drop_index(op.f("ix_promotion_audits_reviewer_id"), table_name="promotion_audits")
    op.drop_index(op.f("ix_promotion_audits_production_document_id"), table_name="promotion_audits")
    op.drop_table("promotion_audits")
    op.drop_index(op.f("ix_diagnostic_turns_session_id"), table_name="diagnostic_turns")
    op.drop_table("diagnostic_turns")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_staged_documents_ingested_by_id"), table_name="staged_documents")
    op.drop_index(op.f("ix_staged_documents_crawl_job_id"), table_name="staged_documents")
    op.drop_table("staged_documents")
    op.drop_index(op.f("ix_diagnostic_sessions_user_id"), table_name="diagnostic_sessions")
    op.drop_table("diagnostic_sessions")
    op.drop_index(op.f("ix_calculation_records_user_id"), table_name="calculation_records")
    op.drop_index(op.f("ix_calculation_records_kind"), table_name="calculation_records")
    op.drop_table("calculation_records")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_index(op.f("ix_crawl_jobs_status"), table_name="crawl_jobs")
    op.drop_index(op.f("ix_crawl_jobs_source_id"), table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    # ### end Alembic commands ###
