"""Flagged answers, and where a queue item came from.

Adds ``flagged_answers`` — a user-reported answer with the question, the
answer, and the retrieved passages **copied at flag time**. Copied rather than
referenced because retrieval over a growing index does not return the same
passages for the same question later, so a reviewer re-running the query would
judge an answer the user was never given.

Also tags every queue item with its ``origin``, so post-launch flags can be
tracked as their own accuracy trend rather than averaged into crawl volume.

Revision ID: e0224010bab8
Revises: 6b538ddb9363
Create Date: 2026-08-27 13:05:59.543624
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e0224010bab8"
down_revision: str | None = "6b538ddb9363"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flagged_answers",
        sa.Column("turn_id", sa.Uuid(), nullable=True),
        sa.Column("flagged_by_id", sa.Uuid(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("retrieved_context", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flagged_by_id"],
            ["users.id"],
            name=op.f("fk_flagged_answers_flagged_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_flagged_answers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["diagnostic_turns.id"],
            name=op.f("fk_flagged_answers_turn_id_diagnostic_turns"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flagged_answers")),
    )
    op.create_index(
        op.f("ix_flagged_answers_flagged_by_id"), "flagged_answers", ["flagged_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_flagged_answers_tenant_id"), "flagged_answers", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_flagged_answers_turn_id"), "flagged_answers", ["turn_id"], unique=False
    )
    # server_default backfills the rows already in the table; every one of
    # them came from the ingestion pipeline, which is what `crawl` means.
    # Dropped straight afterwards so the application stays the only thing that
    # decides a new row's origin.
    op.add_column(
        "verification_items",
        sa.Column("origin", sa.String(length=20), nullable=False, server_default="crawl"),
    )
    op.alter_column("verification_items", "origin", server_default=None)
    op.add_column("verification_items", sa.Column("flagged_answer_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_verification_items_flagged_answer_id"),
        "verification_items",
        ["flagged_answer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_items_origin"), "verification_items", ["origin"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_verification_items_flagged_answer_id_flagged_answers"),
        "verification_items",
        "flagged_answers",
        ["flagged_answer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # Alembic does not diff check constraints, so this is written by hand. A
    # flag-sourced item has neither a chunk nor a staged document, and the
    # existing rule would reject it.
    op.drop_constraint(
        op.f("ck_verification_items_target_present"), "verification_items", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_verification_items_target_present"),
        "verification_items",
        "chunk_id IS NOT NULL OR staged_document_id IS NOT NULL "
        "OR flagged_answer_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_verification_items_target_present"), "verification_items", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_verification_items_target_present"),
        "verification_items",
        "chunk_id IS NOT NULL OR staged_document_id IS NOT NULL",
    )
    op.drop_constraint(
        op.f("fk_verification_items_flagged_answer_id_flagged_answers"),
        "verification_items",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_verification_items_origin"), table_name="verification_items")
    op.drop_index(op.f("ix_verification_items_flagged_answer_id"), table_name="verification_items")
    op.drop_column("verification_items", "flagged_answer_id")
    op.drop_column("verification_items", "origin")
    op.drop_index(op.f("ix_flagged_answers_turn_id"), table_name="flagged_answers")
    op.drop_index(op.f("ix_flagged_answers_tenant_id"), table_name="flagged_answers")
    op.drop_index(op.f("ix_flagged_answers_flagged_by_id"), table_name="flagged_answers")
    op.drop_table("flagged_answers")
    # ### end Alembic commands ###
